<?php

$select_order = "xray_order.uid,
xray_order.acc,
xray_order.patientid, 
xray_order.mrn,
xray_order.name,
xray_order.lastname,
xray_order.weight,
xray_order.contrast,
xray_order.contrast_allergies,
xray_order.address,
xray_order.name_dep,
xray_order.radiographer_id,
xray_order.radiographer_name,
xray_order.dokrad_name,
xray_order.dokradid,
xray_order.dokterid,
xray_order.dep_id,
xray_order.named,
xray_order.lastnamed,
xray_order.create_time,
xray_order.priority,
xray_order.sex,
xray_order.id_prosedur,
xray_order.prosedur,
xray_order.harga_prosedur,
xray_order.birth_date,
xray_order.id_modality,
xray_order.xray_type_code,
xray_order.pat_state,
xray_order.spc_needs,
xray_order.schedule_date,
xray_order.schedule_time,
xray_order.id_payment,
xray_order.payment,
xray_order.examed_at,
xray_order.fromorder,
xray_order.deleted_at,
xray_order.patientid AS no_foto";

$table_order = "$database_ris.xray_order AS xray_order";
